### ISSUE TITLE
Fetch multiple components asynchronously?

### ISSUE THREAD

**Issue by MoritzKemp** [akless/ccm-developer#1]
I was playing around with the performance tab on Google Chrome and noticed that dependencies of a ccm component are not fetched asynchronously. I am using `ccm.instance` for dependency definition.

Is there any reason for that? Because as you may see in the Google Chrome performance tab, the ccm framework stalls instead of moving to the next dependency.

The test component:
```javascript
var component = {
    name: "perf_test",
    ccm: 'https://akless.github.io/ccm/ccm.js',
    config:{
        "inst_1": ["ccm.instance", "https://akless.github.io/ccm-components/blank/ccm.blank.js"],
        "inst_2": ["ccm.instance", "https://akless.github.io/ccm-components/content/versions/ccm.content-2.0.0.js"],
        "inst_3": ["ccm.instance", "https://akless.github.io/ccm-components/eval/versions/ccm.eval-1.0.0.js"],
        "inst_4": ["ccm.instance", "https://akless.github.io/ccm-components/cloze/versions/ccm.cloze-3.2.0.js"]
    },
    Instance: function(){
        let self = this;
        let my = {};
            
        this.ready = function( callback ){
            my = self.ccm.helper.privatize(self);
            if(callback) callback();
        };
            
        this.start = function( callback ){
            console.log("[perf_test] Start-up");
            if(callback) callback();
        };
    }
};
```
Together with this index.html

```html
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://akless.github.io/ccm/ccm.js"></script>
    </head>
    <body>
        <div>TODO write content</div>
        <script>
            ccm.start(
                "./ccm.perf_test.js"
            );
        </script>
    </body>
</html>
```

**Comment by akless** [comment]
You're right. Thank's for reporting. Since _ccm_ v1.0.0 this works in parallel, but today it works serial. I must fix this. I looked at the framework code and i see that this is happening only for `['ccm.instance', ...]` dependencies. If you want to see that _ccm_ do such thing normally in parallel, than simply use `['ccm.component, ...]` dependencies instead. Then you can see the loading in parallel. I will fix this for `['ccm.instance', ...]` dependencies in a later update.

**Comment by akless** [comment]
Fixed since _ccm_ v18.
